// <auto-generated />
namespace Reedly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ReplaceMagicNumbersFromMin18YrsModelWithStaticValuesInMembershipType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReplaceMagicNumbersFromMin18YrsModelWithStaticValuesInMembershipType));
        
        string IMigrationMetadata.Id
        {
            get { return "201806170719144_ReplaceMagicNumbersFromMin18YrsModelWithStaticValuesInMembershipType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
